$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline
display_name: "kfold pipeline"
experiment_name: test_pipeline
settings:
  default_compute: serverless
inputs:
  path_minute_data: 
    type: uri_file
    path: "/home/thomas/repos/simplify_deployment/data/lots_of_vars/minute_data.parquet"
  path_qh_data:
    type: uri_file
    path: "/home/thomas/repos/simplify_deployment/data/lots_of_vars/quarter_data.parquet"
outputs:
  predictions:
    type: uri_folder
jobs:
  create_datasets:
    type: command
    command: >-
      python ./src/simplify_deployment/create_datasets.py
      --path-minute-data=${{inputs.path_minute_data}}
      --path-qh-data=${{inputs.path_qh_data}}
      --path-to-save-folds=${{outputs.path_to_save_folds}}
    code: ..
    environment:
      azureml:simplify_study_phase:1
    environment_variables: 
      PYTHONPATH: src
    inputs:
      path_minute_data:
        type: uri_file
        path: "/home/thomas/repos/simplify_deployment/data/lots_of_vars/minute_data.parquet"
      path_qh_data:
        type: uri_file
        path: "/home/thomas/repos/simplify_deployment/data/lots_of_vars/quarter_data.parquet"
    outputs:
      path_to_save_folds:
        type: uri_folder

  # Define a parallel job for training folds
  train_folds:
    type: parallel
    jobs:
      fold_train:
        type: command
        command: >-
          python ./src/simplify_deployment/predict_single.py
          --path-config=${{inputs.path_config}}
          --path-to-folds=${{inputs.path_to_folds}}
          --fold=${{inputs.fold}}
          --path-best-genome=${{outputs.path_best_genome}}
          --path-to-save-predictions=${{outputs.path_to_save_predictions}}
          --extra-organisms=${{inputs.extra_organisms}}
        code: ..
        environment:
          azureml:simplify_study_phase:1
        environment_variables: 
          PYTHONPATH: src
        inputs:
          path_config:
            type: uri_file
            path: "/home/thomas/repos/simplify_deployment/src/simplify_deployment/config/lag_25_lots_of_vars.yaml"
          path_to_folds:
            type: uri_folder
            path: ${{parent.jobs.create_datasets.outputs.path_to_save_folds}}
          fold: ${fold}
          extra_organisms:
            type: uri_file
            path: "/home/thomas/repos/simplify_deployment/src/simplify_deployment/genomes/lag_25_simplify_1_0.yaml" 
        outputs:
          path_best_genome:
            type: uri_file
          path_to_save_predictions:
            type: uri_folder
            path: ${{parent.outputs.predictions}}

    # Use a parameter to define the number of folds
    parameters:
      fold:
        type: integer
        default: 0
        range: [0, 4]  # Adjust the range to match the number of folds

