- kind: band_pass
  period_hours: 24
  columns: 
    - siCumulative
- kind: band_pass
  period_hours: 12
  columns: 
    - siCumulative
- kind: band_pass
  period_hours: 1
  columns: 
    - siCumulative
- kind: band_pass
  period_hours: 0.25
  columns: 
    - siCumulative
- kind: low_pass
  period_hours: 24
  columns: 
    - siCumulative
- kind: low_pass
  period_hours: 12
  columns: 
    - siCumulative
- kind: low_pass
  period_hours: 1
  columns: 
    - siCumulative
- kind: low_pass
  period_hours: 0.25
  columns: 
    - siCumulative
- kind: high_pass
  period_hours: 24
  columns: 
    - siCumulative
- kind: high_pass
  period_hours: 12
  columns: 
    - siCumulative
- kind: high_pass
  period_hours: 1
  columns: 
    - siCumulative
- kind: high_pass
  period_hours: 0.25
  columns: 
    - siCumulative